### PR TITLE
Fix missing configuration options panics

### LINKED ISSUE #103: Executor won't start when checkpoint is not configured
```
panic: illegal value for minWait: 0s

goroutine 1 [running]:
github.com/allegro/mesos-executor/vendor/github.com/mesos/mesos-go/api/v1/lib/backoff.Notifier(0x3b9aca00, 0x0, 0x0, 0xc42039a840)
	$GOPATH/src/github.com/allegro/mesos-executor/vendor/github.com/mesos/mesos-go/api/v1/lib/backoff/backoff.go:58 +0x1f4
github.com/allegro/mesos-executor.(*Executor).Start(0xc42044c1c0, 0x94a275, 0x10)
	$GOPATH/src/github.com/allegro/mesos-executor/executor.go:176 +0x2c0
main.main()
	$GOPATH/src/github.com/allegro/mesos-executor/cmd/executor/main.go:122 +0x2d3
```

It happen in [executor.Start()](https://github.com/allegro/mesos-executor/blob/v0.11.9/executor.go#L176) becouse `MESOS_SUBSCRIPTION_BACKOFF_MAX` and `MESOS_RECOVERY_TIMEOUT` are only required if `MESOS_CHECKPOINT` is enabled see [`mesos-go executor/config/config.go`](https://github.com/mesos/mesos-go/blob/mesos-1.1.x/api/v1/lib/executor/config/config.go#L85-L89`)

### PR DESCRIPTION
**Pull request by AlfredBroda**
Fixes #103.

### CODE REVIEW

**Comment by janisz** [comment]
It does NOT fixes #103

**Comment by janisz** [comment]
@medzin https://github.com/allegro/mesos-executor/issues/103#issuecomment-376907700

**Comment by medzin** [comment]
I do not see any tests added.

File: cmd/executor/main_test.go [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+			AgentEndpoint: "localhost",
+		},
+	}
+
+	// when
+	err := startExecutor(conf)
+
+	// then
+	assert.Error(t, err)
+	assert.Equal(t, "failed to re-establish subscription with agent within 1s, aborting", err.Error())
```
Comment (medzin) [inline cmd/executor/main_test.go]: How do we know that it will take exactly one second to produce error? In addition, why do we make an assertion for an error message? Changing the text is supposed to fail the tests?

File: cmd/executor/main_test.go [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+import (
+	"testing"
+
+	"github.com/allegro/mesos-executor"
+	"github.com/mesos/mesos-go/api/v1/lib/executor/config"
+	"github.com/stretchr/testify/assert"
+)
+
+func TestExecutorStartsWithoutCheckpointConfig(t *testing.T) {
```
Comment (medzin) [inline cmd/executor/main_test.go]: `TestIf` will look more sensible.

File: cmd/executor/main_test.go [hunk 3]
```diff
@@ -0,0 +1,28 @@
+package main
```
Comment (medzin) [inline cmd/executor/main_test.go]: Add test case for no config.

File: cmd/executor/main.go [hunk 4]
```diff
@@ -101,8 +101,34 @@ func readConfiguration(config interface{}) {
 	}
 }
 
+func startExecutor(conf executor.Config) error {
```
Comment (medzin) [inline cmd/executor/main.go]: Move this code to the `executor` package.

File: cmd/executor/main_test.go [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+			ExecutorID:  "executor",
+			AgentEndpoint: "localhost",
+		},
+	}
+
+	// when
+	err := startExecutor(conf)
+
+	// then
+	assert.Error(t, err)
```
Comment (medzin) [inline cmd/executor/main_test.go]: I think we need also a [NotPanics](https://godoc.org/github.com/stretchr/testify/assert#NotPanics) assertion here - we fixing bug that code is panicking when some config options are missing.

File: cmd/executor/main.go (hunk 4 above)
Comment (AlfredBroda) [reply cmd/executor/main.go]: This would create an import cycle. Unless the hook code stays here...

File: cmd/executor/main_test.go (hunk 3 above)
Comment (AlfredBroda) [reply cmd/executor/main_test.go]: Actually, the case you mention covers this error too, so I will make the existing test more general (ie. test a no config situation).

File: cmd/executor/main_test.go (hunk 1 above)
Comment (AlfredBroda) [reply cmd/executor/main_test.go]: Done.

File: executor_test.go [hunk 6]
```diff
@@ -382,6 +381,12 @@ func TestIfNotPanicsWhenKillWithoutLaunch(t *testing.T) {
 	})
 }
 
+func TestIfExecutorStartsWithoutConfig(t *testing.T) {
```
Comment (medzin) [inline executor_test.go]: It should just start and don't panic or return error also?
